version: '3'
services:
  selenium:
    image: selenium/standalone-chrome
    restart: always
    ports:
    - '4444:4444'
  mftf:
    build:
      context: .
    entrypoint: vendor/bin/mftf run:group PWA1
    volumes:
      - ./dev/tests/acceptance/tests:/usr/src/app/dev/tests/acceptance/tests
    links:
    - selenium

